package service

import (
	"strings"
	"unicode"

	"lawyer-bot/internal/domain"
)

// Composer turns a Decision into the exact text the user receives.
//
// Replies are built from templates rather than generated by the model. That
// keeps answers short, keeps the wording under business control, and makes it
// structurally impossible for the model to invent a price.
type Composer struct {
	catalog *Catalog
}

// NewComposer builds a Composer.
func NewComposer(catalog *Catalog) *Composer {
	return &Composer{catalog: catalog}
}

// Compose renders the reply. It returns "" when there is nothing to say, which
// the pipeline treats as silence.
func (c *Composer) Compose(d Decision, lang domain.Language, aiQuestion string) string {
	lang = lang.OrDefault()

	switch d.Action {
	case ActionServiceMenu:
		return c.serviceMenu(lang)

	case ActionClarify:
		if q := c.clarify(d.Service, lang, aiQuestion); q != "" {
			return q
		}
		return c.serviceMenu(lang)

	case ActionServiceInfo:
		return c.serviceInfo(d.Service, lang)

	case ActionAskContact:
		return tr(lang, contactRequest)

	case ActionHandoff:
		return tr(lang, handoffOffer)

	default:
		return ""
	}
}

// clarify picks the shortest safe clarification question: the model's own
// suggestion when it passes validation, otherwise the catalog's configured one.
func (c *Composer) clarify(serviceCode string, lang domain.Language, aiQuestion string) string {
	if q, ok := SanitizeQuestion(aiQuestion); ok {
		if s, found := c.catalog.Get(serviceCode); found {
			return tr(lang, acknowledgeService) + " " + s.Name(lang) + ".\n\n" + q
		}
		return q
	}
	if s, found := c.catalog.Get(serviceCode); found {
		if q := s.ClarifyQuestion(lang); q != "" {
			return tr(lang, acknowledgeService) + " " + s.Name(lang) + ".\n\n" + q
		}
	}
	return tr(lang, genericClarify)
}

// serviceInfo states the identified service, explains that the cost depends on
// complexity and offers the handoff. It never contains a number unless the
// catalog explicitly configures a fixed price for that service.
func (c *Composer) serviceInfo(serviceCode string, lang domain.Language) string {
	var b strings.Builder

	if s, ok := c.catalog.Get(serviceCode); ok {
		b.WriteString(tr(lang, acknowledgeService))
		b.WriteString(" ")
		b.WriteString(s.Name(lang))
		b.WriteString(".\n\n")

		if price := s.Price(lang); price != "" {
			b.WriteString(price)
		} else {
			b.WriteString(tr(lang, priceDependsOnComplexity))
		}
		b.WriteString("\n\n")
	} else {
		b.WriteString(tr(lang, priceDependsOnComplexity))
		b.WriteString("\n\n")
	}

	b.WriteString(tr(lang, handoffOffer))
	return b.String()
}

// serviceMenu is the short "what exactly do you need?" prompt.
func (c *Composer) serviceMenu(lang domain.Language) string {
	return tr(lang, serviceMenuText)
}

// SanitizeQuestion validates a clarification question produced by the model.
// It is rejected when it is empty, too long, not a question, or when it looks
// like it contains a price. Returning false makes the caller fall back to a
// template, so a hallucinated number can never reach the customer.
func SanitizeQuestion(q string) (string, bool) {
	q = strings.TrimSpace(q)
	if q == "" {
		return "", false
	}
	// Keep replies short: one sentence, one question.
	if len([]rune(q)) > 220 {
		return "", false
	}
	if !strings.Contains(q, "?") && !strings.Contains(q, "؟") {
		return "", false
	}

	lower := strings.ToLower(q)
	for _, token := range priceTokens {
		if strings.Contains(lower, token) {
			return "", false
		}
	}
	// Any run of three or more digits looks like an amount.
	run := 0
	for _, r := range q {
		if unicode.IsDigit(r) {
			run++
			if run >= 3 {
				return "", false
			}
			continue
		}
		run = 0
	}
	return q, true
}

// priceTokens are markers of monetary content. Their presence in model output
// disqualifies the text: pricing is a human decision.
var priceTokens = []string{
	"тг", "₸", "тенге", "kzt", "теңге", "руб", "₽", "rub",
	"$", "usd", "доллар", "€", "eur", "евро",
	"тыс.", "тысяч", "мың теңге", "стоит", "стоимость составля", "цена составля",
	"price is", "costs ", "мың тг",
}

// tr picks the translation for a language, falling back to Russian.
func tr(lang domain.Language, table map[domain.Language]string) string {
	if s, ok := table[lang.OrDefault()]; ok {
		return s
	}
	return table[domain.LangRU]
}

var serviceMenuText = map[domain.Language]string{
	domain.LangRU: "Здравствуйте! Подскажите, пожалуйста, что именно вас интересует:\n\n" +
		"™️ Товарный знак\n" +
		"💼 Регистрация бизнеса\n" +
		"📄 Договоры\n" +
		"🌐 Документы для сайта или приложения\n" +
		"📝 Политика конфиденциальности\n" +
		"⚖️ Другая юридическая услуга",
	domain.LangKK: "Сәлеметсіз бе! Сізді нақты не қызықтыратынын айтыңызшы:\n\n" +
		"™️ Тауар белгісі\n" +
		"💼 Бизнесті тіркеу\n" +
		"📄 Шарттар\n" +
		"🌐 Сайт немесе қосымшаға арналған құжаттар\n" +
		"📝 Құпиялылық саясаты\n" +
		"⚖️ Басқа заңгерлік қызмет",
	domain.LangEN: "Hello! Could you tell us what exactly you need:\n\n" +
		"™️ Trademark\n" +
		"💼 Business registration\n" +
		"📄 Contracts\n" +
		"🌐 Website or application documents\n" +
		"📝 Privacy policy\n" +
		"⚖️ Another legal service",
}

var acknowledgeService = map[domain.Language]string{
	domain.LangRU: "Понял, вас интересует:",
	domain.LangKK: "Түсіндім, сізді қызықтыратыны:",
	domain.LangEN: "Understood, you need:",
}

var genericClarify = map[domain.Language]string{
	domain.LangRU: "Подскажите, пожалуйста, что именно требуется?",
	domain.LangKK: "Нақты не қажет екенін айтыңызшы?",
	domain.LangEN: "Could you tell us what exactly you need?",
}

// priceDependsOnComplexity is the mandatory wording whenever a service has no
// explicitly configured fixed price.
var priceDependsOnComplexity = map[domain.Language]string{
	domain.LangRU: "Стоимость зависит от сложности задачи, объема работ и конкретного направления. " +
		"После уточнения деталей специалист сможет определить стоимость.",
	domain.LangKK: "Қызмет құны жұмыстың күрделілігіне, жұмыс көлеміне және нақты бағытына байланысты. " +
		"Мәліметтер нақтыланғаннан кейін маман нақты құнын анықтай алады.",
	domain.LangEN: "The final cost depends on the complexity, scope of work, and specific requirements. " +
		"The specialist can determine the exact cost after reviewing the details.",
}

var handoffOffer = map[domain.Language]string{
	domain.LangRU: "Могу передать ваш запрос специалисту Диане для уточнения деталей.",
	domain.LangKK: "Сұранысыңызды маман Дианаға мәліметтерді нақтылау үшін жібере аламын.",
	domain.LangEN: "I can pass your request to our specialist Diana to discuss the details.",
}

var contactRequest = map[domain.Language]string{
	domain.LangRU: "Чтобы специалист мог связаться с вами, отправьте, пожалуйста, ваш номер телефона.",
	domain.LangKK: "Маман сізбен байланысуы үшін телефон нөміріңізді жіберіңіз.",
	domain.LangEN: "Please provide your phone number so our specialist can contact you.",
}
